version: '3.1'

services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: asshole
      POSTGRES_USER: emptyproject-user
      POSTGRES_DB: emptyproject-db

  application:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    restart: always

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - 80:80
    restart: always
