# don't know why 3.1, but why not
version: '3.1'

services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: asshole
      POSTGRES_USER: emptyproject-user
      POSTGRES_DB: emptyproject-db

  application:
    # our Dockerfiles are not located in our build context directory
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    restart: always
    depends_on:
      - database
    # docker-entrypoint.sh is already inside the container
    entrypoint: /docker-entrypoint.sh

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - 80:80
    restart: always
    depends_on:
      - application
