version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: asshole

  application:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    restart: always

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - 80:80
    restart: always
