version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: asshole

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  application:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - 80:80
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    restart: always
